### ISSUE TITLE
0.2.9 breaks build with class not found exceptions

### ISSUE THREAD

**Issue by jansorg** [JetBrains/gradle-intellij-plugin#202]
My plugin is building fine with 0.2.7.

The build breaks after I update to 0.2.8 or 0.2.9.

The build.gradle file uses 
intellij.version 'IC-2016.1.4' and the python-community plugin as dependency.

If you need more information, please let me know.

I get a lot of failed tests, most of them print a Class not found exception, e.g. 

```
    java.lang.NoClassDefFoundError: Could not initialize class com.intellij.openapi.vfs.newvfs.ManagingFS$ManagingFSHolder
```

Other exceptions:

```
java.lang.NoClassDefFoundError: Could not initialize class com.intellij.openapi.vfs.newvfs.ManagingFS$ManagingFSHolder
	at com.intellij.openapi.vfs.newvfs.ManagingFS.getInstance(ManagingFS.java:35)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFS.getInstance(PersistentFS.java:52)
	at com.intellij.testFramework.LightPlatformTestCase.cleanPersistedVFSContent(LightPlatformTestCase.java:224)
	at com.intellij.testFramework.LightPlatformTestCase.access$100(LightPlatformTestCase.java:123)
	at com.intellij.testFramework.LightPlatformTestCase$2.run(LightPlatformTestCase.java:237)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1009)
	at com.intellij.testFramework.LightPlatformTestCase.initProject(LightPlatformTestCase.java:230)
	at com.intellij.testFramework.LightPlatformTestCase.doSetup(LightPlatformTestCase.java:313)
	at com.intellij.testFramework.fixtures.impl.LightIdeaTestFixtureImpl.setUp(LightIdeaTestFixtureImpl.java:53)
	at com.intellij.testFramework.fixtures.impl.CodeInsightTestFixtureImpl$26.run(CodeInsightTestFixtureImpl.java:1354)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:26)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:24)
	at com.intellij.testFramework.EdtTestUtilKt.runInEdtAndWait(EdtTestUtil.kt:42)
	at com.intellij.testFramework.EdtTestUtil$Companion.runInEdtAndWait(EdtTestUtil.kt:26)
	at com.intellij.testFramework.EdtTestUtil.runInEdtAndWait(EdtTestUtil.kt)
	at com.intellij.testFramework.fixtures.impl.CodeInsightTestFixtureImpl.setUp(CodeInsightTestFixtureImpl.java:1351)
	at com.intellij.testFramework.fixtures.LightPlatformCodeInsightFixtureTestCase.setUp(LightPlatformCodeInsightFixtureTestCase.java:61)
```

The last output of "gradle clean build" is
```
ERROR: com.intellij.configurationStore.StoreAwareProjectManager has unsatisfied dependency: class com.intellij.openapi.progress.ProgressManager among unsatisfiable dependencies: [[class com.intellij.openapi.vfs.VirtualFileManager, class com.intellij.openapi.progress.ProgressManager]] where DefaultPicoContainer (root) was the leaf container being asked for dependencies.
org.picocontainer.defaults.UnsatisfiableDependenciesException: com.intellij.configurationStore.StoreAwareProjectManager has unsatisfied dependency: class com.intellij.openapi.progress.ProgressManager among unsatisfiable dependencies: [[class com.intellij.openapi.vfs.VirtualFileManager, class com.intellij.openapi.progress.ProgressManager]] where DefaultPicoContainer (root) was the leaf container being asked for dependencies.
        at com.intellij.util.pico.ConstructorInjectionComponentAdapter.getGreediestSatisfiableConstructor(ConstructorInjectionComponentAdapter.java:114)
        at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:210)
        at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
        at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
        at com.intellij.util.pico.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:59)
        at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:499)
        at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponent(ComponentManagerImpl.java:184)
        at com.intellij.openapi.project.ex.ProjectManagerEx.getInstanceEx(ProjectManagerEx.java:31)
        at com.intellij.openapi.application.impl.ApplicationImpl.disposeSelf(ApplicationImpl.java:275)
        at com.intellij.openapi.application.impl.ApplicationImpl.access$400(ApplicationImpl.java:92)
        at com.intellij.openapi.application.impl.ApplicationImpl$5$1.run(ApplicationImpl.java:264)
        at com.intellij.openapi.util.ShutDownTracker$2.run(ShutDownTracker.java:172)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:857)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
ERROR: com.intellij.configurationStore.StoreAwareProjectManager has unsatisfied dependency: class com.intellij.openapi.progress.ProgressManager among unsatisfiable dependencies: [[class com.intellij.openapi.vfs.VirtualFileManager, class com.intellij.openapi.progress.ProgressManager]] where DefaultPicoContainer (root) was the leaf container being asked for dependencies.
java.lang.AssertionError: com.intellij.configurationStore.StoreAwareProjectManager has unsatisfied dependency: class com.intellij.openapi.progress.ProgressManager among unsatisfiable dependencies: [[class com.intellij.openapi.vfs.VirtualFileManager, class com.intellij.openapi.progress.ProgressManager]] where DefaultPicoContainer (root) was the leaf container being asked for dependencies.
        at com.intellij.testFramework.LoggedErrorProcessor.processError(LoggedErrorProcessor.java:56)
        at com.intellij.testFramework.TestLogger.error(TestLogger.java:38)
        at com.intellij.openapi.diagnostic.Logger.error(Logger.java:146)
        at com.intellij.ide.plugins.PluginManager.processException(PluginManager.java:144)
        at com.intellij.ide.IdeEventQueue.processException(IdeEventQueue.java:407)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:860)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.AssertionError: com.intellij.configurationStore.StoreAwareProjectManager has unsatisfied dependency: class com.intellij.openapi.progress.ProgressManager among unsatisfiable dependencies: [[class com.intellij.openapi.vfs.VirtualFileManager, class com.intellij.openapi.progress.ProgressManager]] where DefaultPicoContainer (root) was the leaf container being asked for dependencies.
        at com.intellij.testFramework.LoggedErrorProcessor.processError(LoggedErrorProcessor.java:56)
        at com.intellij.testFramework.TestLogger.error(TestLogger.java:38)
        at com.intellij.openapi.diagnostic.Logger.error(Logger.java:146)
        at com.intellij.ide.plugins.PluginManager.processException(PluginManager.java:144)
        at com.intellij.ide.IdeEventQueue.processException(IdeEventQueue.java:407)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:389)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```
