### ISSUE TITLE
runIde fails with IU-LATEST-EAP-SNAPSHOT IU-223.6160.11 - Unable to find class: YJ↨☺☺P - NoClassDefFoundError: Could not initialize class com.sun.jna.Native

### ISSUE THREAD

**Issue by jonathanlermitage** [JetBrains/gradle-intellij-plugin#1154]
**Describe the bug**
Can't run (runIde) an IJ plugin with IU-LATEST-EAP-SNAPSHOT. I get the following logs (please see attached log file 
[trace.log](https://github.com/JetBrains/gradle-intellij-plugin/files/9742641/trace.log)
), and the task finally hangs. I have to quit with Ctrl+C.  
Nota: this problem is very new. It was OK last week (exact same project and same Gradle IntelliJ Plugin Version). The JetBrains plugin portal was down (5xx error) yesterday or 2 days ago, I don't remember, and the error appeared once the portal has been restored. This is probably a coincidence, but I prefered to mention it.

**To Reproduce**
Check out [this project](https://github.com/jonathanlermitage/intellij-extra-icons-plugin) and run `gradlew runIde -PpluginIdeaVersion=IU-LATEST-EAP-SNAPSHOT -PpluginJavaVersion=17`

**Environment:**
 - OS: Windows 10 x64
 - Gradle IntelliJ Plugin Version: 1.9.0
 - Gradle Version: 7.5.1

**Comment by jonathanlermitage** [comment]
Nota: I purged my idea sandbox directory. The `Unable to find class: YJ↨☺☺P` is gone, but I still see `NoClassDefFoundError: Could not initialize class com.sun.jna.Native`, and the task hangs. 
[trace.log](https://github.com/JetBrains/gradle-intellij-plugin/files/9742659/trace.log)

**Comment by YannCebron** [comment]
please try using SNAPSHOT version as described in #1153

**Comment by jonathanlermitage** [comment]
Thank you! I confirm it works with plugin 1.10.0-SNAPSHOT :+1:
