### ISSUE TITLE
Some strange Kotlin build errors since upgrading to 2016.1

### ISSUE THREAD

**Issue by patflynn** [JetBrains/gradle-intellij-plugin#85]
After installing IJ 2016.1 into a machine our  all of our [project's](https://github.com/GoogleCloudPlatform/gcloud-intellij) PlatformTestCase based test cases start failing with an unexpected Kotlin error.

Is it possible that the gradle-intellij-plugin is using the Kotlin bundled with the locally installed IDE instead of the plugin configured IDEA version?

```

java.lang.NoSuchMethodError: kotlin.PreconditionsKt.assert(Z)V
	at com.intellij.configurationStore.ProjectStoreImpl.<init>(ProjectStoreImpl.kt:148)
	at com.intellij.configurationStore.ProjectWithModulesStoreImpl.<init>(ProjectStoreImpl.kt:318)
	at sun.reflect.GeneratedConstructorAccessor19.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:220)
	at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
	at com.intellij.util.pico.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:59)
	at com.intellij.openapi.project.impl.ProjectImpl$2.getComponentInstance(ProjectImpl.java:184)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:246)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:212)
	at com.intellij.openapi.components.ServiceKt.getStateStore(service.kt:29)
	at com.intellij.openapi.project.impl.ProjectImpl.getStateStore(ProjectImpl.java:202)
	at com.intellij.openapi.project.impl.ProjectImpl.<init>(ProjectImpl.java:95)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.a(ProjectManagerImpl.java:245)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.newProject(ProjectManagerImpl.java:183)
	at com.intellij.testFramework.PlatformTestCase.createProject(PlatformTestCase.java:269)
	at com.intellij.testFramework.PlatformTestCase.createProject(PlatformTestCase.java:260)
	at com.intellij.testFramework.PlatformTestCase.doCreateProject(PlatformTestCase.java:255)
	at com.intellij.testFramework.PlatformTestCase.setUpProject(PlatformTestCase.java:240)
	at com.intellij.testFramework.PlatformTestCase.setUp(PlatformTestCase.java:208)
	at com.google.gct.idea.appengine.cloud.ManagedVmCloudConfigurableTest.setUp(ManagedVmCloudConfigurableTest.java:54)
	at com.intellij.testFramework.PlatformTestCase$4.run(PlatformTestCase.java:651)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:25)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:23)
	at com.intellij.testFramework.EdtTestUtilKt$sam$Runnable$a15fd9f8.run(EdtTestUtil.kt)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.c(IdeEventQueue.java:866)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by zolotov** [comment]
I believe you have replaced kotlin.jar in gradle caches. See #69 for details.

Just drop gradle caches `~/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea` and run again.

**Comment by patflynn** [comment]
That fixed it. Thanks!
