### ISSUE TITLE
NoSuchMethodError (org.assertj.core.api.Assertions.assertThat(java.util.Collection)) after upgrade to 1.13.2

### ISSUE THREAD

**Issue by sewe** [JetBrains/gradle-intellij-plugin#1346]
**Describe the bug**

Upgrading from version 1.13.1 to version 1.13.2 (containing https://github.com/JetBrains/gradle-intellij-plugin/issues/1332) causes one (and only one) of our tests using AssertJ to fail with a `NoSuchMethodError`:

```
  Test testAddingServers() FAILED

  java.lang.NoSuchMethodError: 'org.assertj.core.api.AbstractCollectionAssert org.assertj.core.api.Assertions.assertThat(java.util.Collection)'
```

Other tests using AssertJ (but likely different assertions) run fine.

The output of the `dependencies` task, for both plugin versions, is identical. In all cases, there should be `org.assertj:assertj-core:3.24.2` on the `testRuntimeClasspath`.

**Environment:**

Gradle IntelliJ Plugin Version: 1.13.2
Gradle: 7.6
Kotlin: 1.7.10
Groovy: 3.0.13
Ant: Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM: 17.0.6 (Debian 17.0.6+10-Debian-1deb11u1)
OS: Linux 5.10.0-21-amd64 amd64le

**Comment by hsz** [comment]
Can you please try the `1.13.3-SNAPSHOT` [snapshot release](https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin.html#snapshot-release)?

**Comment by hsz** [comment]
Regression in another place. :(
More integration tests will be provided to avoid such issues in the future.
